pipeline {
    agent any
    
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('docker-token')
        DOCKER_IMAGE = 'VaniaUlimazRivani/buku'
    }
    
    stages {
        stage('Build & Docker Push') {
            steps {
                dir('perpustakaan/buku') {
                    echo "🛠️ Memulai kompilasi JAR..."
                    sh './mvnw clean package -DskipTests'
                    
                    echo "🐳 Membangun Docker Image..."
                    sh "docker build -t ${DOCKER_IMAGE}:latest ."
                    
                    echo "🚀 Mengirim ke Docker Hub..."
                    sh 'echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin'
                    sh "docker push ${DOCKER_IMAGE}:latest"
                }
            }
        }
    }
    
    post {
        success {
            echo "✅ Selesai! Image terbaru sudah ada di Docker Hub."
        }
    }
}